feat: create clap de fin article
Barbapapazes/le-classement.fr pull request #106
Opened 2022-12-13 23:15 UTC by Barbapapazes

2022-12-13 23:22 UTC, Barbapapazes commented
Améliorer la qualité de l'image (ne pas trop dégrader quand même

2022-12-14 10:13 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +    alt: Photo du pitch de l'association Course Croisière EDHEC sur scène avec sa présentation dans le fond
```suggestion
    alt: Photo du pitch de l'association La Course Croisière EDHEC sur scène avec sa présentation dans le fond
```

2022-12-14 10:14 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +    alt: Photo du pitch de l'association Les Enfoiros de l'INSA Toulouse sur scène avec sa présentation dans le fond
```suggestion
    alt: Photo du pitch de l'association Les Enfoiros de l'INSA sur scène avec sa présentation dans le fond
```

2022-12-14 10:14 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 13 | Tutorat Associatif Toulousain |
```suggestion
| 13 | Le Tutorat Associatif Toulousain |
```

2022-12-14 10:15 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +    alt: Photo du pitch de l'association Le Chti sur scène avec sa présentation dans le fond
```suggestion
    alt: Photo du pitch de l'association Le Chti Grand Lille sur scène avec sa présentation dans le fond
```

2022-12-14 10:15 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 4 | Course Croisière EDHEC |
```suggestion
| 4 | La Course Croisière EDHEC |
```

2022-12-14 10:15 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 16 | Nuit de l’Institut |
```suggestion
| 16 | La Nuit de l’Institut |
```

2022-12-14 10:16 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +## Gala
```suggestion
## Le gala
```

2022-12-14 10:18 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +- [Le Monde des Grandes Écoles](https://www.mondedesgrandesecoles.fr/)
```suggestion
- [Le Monde des Grandes Écoles](https://www.mondedesgrandesecoles.fr/)
- [Teewii](https://www.teewii.fr/)
```

2022-12-14 16:41 UTC, evartistique requested changes

2022-12-14 16:41 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 4 | **La Course Croisière EDHEC** | EDHEC |
```suggestion
| 4 | **La Course Croisière EDHEC** | EDHEC Business School |
```

2022-12-14 16:41 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 5 | **Le Chti Grand Lille** | EDHEC |
```suggestion
| 5 | **Le Chti Grand Lille** | EDHEC Business School |
```

2022-12-14 16:41 UTC, evartistique commented on content/5.blog/clap-de-fin-2022.md
> +| 1 | **Sup’Bio Dance** | EPITA |
```suggestion
| 1 | **Sup’Bio Dance** | EPITA, Epitech, Sup'Biotech |
```

2022-12-14 20:36 UTC, Barbapapazes commented on content/5.blog/clap-de-fin-2022.md
> +Quelques mots de Marion, co-présidente de l'association, et Yanne, vice-présidente :
```suggestion
Quelques mots de Marion, présidente de l'association, et Yanne, vice-président :
```

2022-12-14 21:08 UTC, merged