refactor: faq
Barbapapazes/le-classement.fr pull request #89
Opened 2022-12-10 15:23 UTC by Barbapapazes

fix #76

2022-12-11 12:46 UTC, evartistique commented on content/8.faq.md
> +  Associer votre image au Classement des Associations, vous permettra de développer votre marque employeur auprès des étudiants, futurs candidats et potentiels talents, des grandes écoles et universi
Associer votre image au Classement des Associations vous permettra de développer votre marque employeur auprès des étudiants, futurs candidats et potentiels talents, des grandes écoles et universités.

2022-12-12 09:35 UTC, Barbapapazes commented
@evartistique j'ai écrit toutes les autres questions.

2022-12-30 10:03 UTC, esoubiran-aneo commented on content/9.faq.md
> +  Le Classement des Associations est un concours national qui vise à rassembler, promouvoir et valoriser la vie association étudiante. Il est découpé en différents étapes :
Changer ce texte par celui de LinkedIn

2022-12-30 10:15 UTC, Barbapapazes commented
Il faut complètement rework les sections pour les faire correspondre à ce qu'est le concours.

2022-12-31 15:51 UTC, evartistique requested changes

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +Retrouve toutes les réponses aux questions que tu te poses<br />sur le Classement des Associations.
```suggestion
Retrouvez toutes les réponses aux questions que vous vous posez<br />sur le Classement des Associations.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Pour en savoir plus, consulter [nos plaquettes](https://le-classement.fr/le-pense-bete).
```suggestion
  Pour en savoir plus, consultez [nos plaquettes](https://le-classement.fr/le-pense-bete).
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Comment se déroule le Classement des Associations ?
A corriger @evartistique

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Quand début le Classement des Associations ?
```suggestion
  Quand débute le Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Les inscriptions débuterons le 1er mars 2023 et se termineront le 15 juin 2023.
```suggestion
  Les inscriptions débuteront le 1er mars 2023 et se termineront le 15 juin 2023.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Le Classement des Associations se termine le 1er décembre 2023.
```suggestion
  Le Classement des Associations se termine le 1er décembre 2023 avec la Cérémonie finale.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Les inscriptions débuterons le 1er mars 2023 et se termineront le 15 juin 2023.
```suggestion
  Les inscriptions débuteront le 1er mars 2023 et se termineront le 15 juin 2023.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Les inscriptions se termine le 15 juin 2023.
```suggestion
  Les inscriptions se termineront le 15 juin 2023.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Quand se termine les inscriptions pour le Classement des Associations ?
```suggestion
  Quand se terminent les inscriptions pour le Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Quand commence les inscriptions pour le Classement des Associations ?
```suggestion
  Quand commencent les inscriptions pour le Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Pour t'inscrire au Classement des Associations, il te suffit de remplir le formulaire d'inscription disponible sur la page [Inscription](). Tu recevras ensuite un mail de confirmation de ton inscri
```suggestion
  Pour s'inscrire au Classement des Associations, il suffit de remplir le formulaire d'inscription disponible sur la page [Inscription](). Vous recevrez ensuite un mail de confirmation de l'inscription.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Après ton inscription, tu recevras un mail dans un délai de 7 jours maximals. Si tu ne reçois pas de mail, cela signifie que ton inscription n'a pas été prise en compte. Tu peux alors nous contacte
```suggestion
  Après votre inscription, vous recevrez un mail dans un délai de 7 jours maximaux. Si vous ne recevez pas de mail, cela signifie que votre inscription n'a pas été prise en compte. Vous pouvez alors nous contacter à l'adresse [contact@le-classement.fr](mailto:contact@le-classement.fr)
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Comment savoir si mon association est inscrite au Classement des Associations ?
```suggestion
  Comment savoir si son association est inscrite au Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Comment puis-je inscrire mon association au Classement des Associations ?
```suggestion
  Comment inscrire son association au Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Comment puis-je contacter les organisateurs du Classement des Associations ?
```suggestion
  Comment contacter les organisateurs du Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Pour contacter les organisateurs du Classement des Associations, tu peux nous envoyer un mail à l'adresse [contact@le-classement.fr](mailto:contact@le-classement.fr).
```suggestion
  Pour contacter les organisateurs du Classement des Associations, vous pouvez nous envoyer un mail à l'adresse [contact@le-classement.fr](mailto:contact@le-classement.fr).
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Tu peux aussi nous contacter via les réseaux sociaux ou via le formulaire présent sur la page [Contact](/nous-contacter).
```suggestion
  Vous pouvez aussi nous contacter via les réseaux sociaux ou via le formulaire présent sur la page [Contact](/nous-contacter).
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Tu peux trouver tous les liens utils et importants pour le Classement des Associations sur la page [/le-pense-bete](/le-pense-bete).
```suggestion
  Tous les liens importants pour le Classement des Associations se trouvent sur la page [/le-pense-bete](/le-pense-bete).
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Comment puis-je devenir partenaire du Classement des Associations ?
```suggestion
  Comment devenir partenaire du Classement des Associations ?
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  En devenant partenaire du Classement des Associations, différenciez-vous de la concurrence. Toucher notre communauté d’étudiants, partager vos valeurs, dévoiler votre vision et devenez la référence
```suggestion
  En devenant partenaire du Classement des Associations, différenciez-vous de la concurrence. Touchez notre communauté d’étudiants, partagez vos valeurs, dévoilez votre vision et devenez la référence dans votre domaine auprès de vos futurs consommateurs, clients et collaborateurs qui vous permettront demain de faire grandir et évoluer votre entreprise.
```

2022-12-31 15:51 UTC, evartistique commented on content/9.faq.md
> +  Associer votre image au Classement des Associations vous permettra de développer votre marque employeur auprès des étudiants, futurs candidats et potentiels talents, des grandes écoles et universit
```suggestion
  Associer votre image au Classement des Associations vous permettra de développer votre marque employeur auprès des étudiants, futurs candidats et potentiels talents des grandes écoles et universités.
```

2023-01-15 19:59 UTC, Barbapapazes commented on content/9.faq.md
> +description: Retrouve toutes les réponses aux questions que tu te poses sur le Classement des Associations.
```suggestion
description: Retrouvez toutes les réponses aux questions que vous vous posez sur le Classement des Associations.
```

2023-01-15 22:05 UTC, merged